[package]
name = "librespot-audio"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]
description="The audio fetching and processing logic for librespot"
license="MIT"

[dependencies.librespot-core]
path = "../core"
version = "0.1.0"

[dependencies]
bit-set = "0.5"
byteorder = "1.3"
bytes = "0.4"
futures = "0.1"
lewton = "0.9"
log = "0.4"
num-bigint = "0.2"
num-traits = "0.2"
tempfile = "3.1"
aes-ctr = "0.3"
vorbis = { version ="0.1.0", optional = true }

[dependencies.librespot-tremor]
version = "0.1.0"
optional = true
git = "https://github.com/sabino/librespot-tremor"
branch = "master"

[features]
with-tremor = ["librespot-tremor"]
with-vorbis = ["vorbis"]
